### ISSUE TITLE
Структурирование требование.

### ISSUE THREAD

**Issue by LazarevSergey** [AnnMalofeeva/Sudoku#1]
Пожалуй перенесу традицию "Не засерай основной поток документов"
Оценивайте.
[Structur_treb.docx](https://github.com/AnnMalofeeva/Sudoku/files/7221/Structur_treb.docx)

**Comment by AnnMalofeeva** [comment]
Поправь, пожалуйста. 
[Structur_treb.docx](https://github.com/AnnMalofeeva/Sudoku/files/7226/Structur_treb.docx)

**Comment by LazarevSergey** [comment]
[Structur_treb(v.1.1).docx](https://github.com/AnnMalofeeva/Sudoku/files/7854/Structur_treb.v.1.1.docx)
оцениваем и пишем

**Comment by AnnMalofeeva** [comment]
назначение мне все еще не нравится, будем надеяться, прокатит.
